#!/usr/bin/env python3
"""Deterministic orchestration commands for the GodoGen Codex skill."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

ARTIFACT_DIR = Path("artifacts/godogen")


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def run(command: list[str], cwd: Path, log: Path, timeout: int = 300) -> dict[str, Any]:
    started = time.time()
    executable = shutil.which(command[0])
    if executable is None:
        result = {"command": command, "exit_code": 127, "duration_seconds": 0, "stdout": "", "stderr": f"{command[0]} not found on PATH"}
    else:
        try:
            completed = subprocess.run(command, cwd=cwd, text=True, capture_output=True, check=False, timeout=timeout)
            result = {
                "command": command,
                "exit_code": completed.returncode,
                "duration_seconds": round(time.time() - started, 3),
                "stdout": completed.stdout,
                "stderr": completed.stderr,
            }
        except subprocess.TimeoutExpired as exc:
            result = {"command": command, "exit_code": 124, "duration_seconds": round(time.time() - started, 3), "stdout": exc.stdout or "", "stderr": f"Timed out after {timeout}s"}
    log.parent.mkdir(parents=True, exist_ok=True)
    log.write_text(
        "$ " + " ".join(command) + "\n\nSTDOUT\n" + result["stdout"] + "\n\nSTDERR\n" + result["stderr"],
        encoding="utf-8",
    )
    return result


def ensure_project(path: Path) -> None:
    if not path.is_dir() or not (path / "project.godot").is_file():
        raise SystemExit(f"Not a Godot project: {path}")


def project_language(path: Path) -> str:
    if list(path.glob("*.csproj")) or any(path.rglob("*.cs")):
        return "csharp"
    if any(path.rglob("*.gd")):
        return "gdscript"
    return "unknown"


def safe_target(path: Path, allow_non_empty: bool) -> None:
    resolved = path.resolve()
    forbidden = {Path(resolved.anchor), Path.home().resolve(), Path.cwd().resolve().parent}
    if resolved in forbidden or len(resolved.parts) < 3:
        raise SystemExit(f"Refusing unsafe target: {resolved}")
    if resolved.exists() and any(resolved.iterdir()) and not allow_non_empty:
        raise SystemExit("Target is not empty. Pass --allow-non-empty only after reviewing its contents.")


def bootstrap(args: argparse.Namespace) -> int:
    target = Path(args.target).expanduser().resolve()
    safe_target(target, args.allow_non_empty)
    target.mkdir(parents=True, exist_ok=True)
    created: list[str] = []

    def create(relative: str, content: str) -> None:
        destination = target / relative
        if destination.exists():
            return
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        created.append(relative)

    create("project.godot", f'; Generated by GodoGen\nconfig_version=5\n\n[application]\nconfig/name="{args.name}"\nrun/main_scene="res://scenes/Main.tscn"\n\n[display]\nwindow/size/viewport_width=1280\nwindow/size/viewport_height=720\n\n[rendering]\nrenderer/rendering_method="gl_compatibility"\n')
    create("scenes/Main.tscn", '[gd_scene format=3]\n\n[node name="Main" type="Node"]\n')
    create("README.md", f"# {args.name}\n\nGenerated with GodoGen. Open `project.godot` in Godot or run `godot --path .`.\n")
    create(".gitignore", ".godot/\nartifacts/godogen/\nbin/\nobj/\n")
    if args.language == "gdscript":
        create("scripts/main.gd", "extends Node\n\nfunc _ready() -> void:\n    print(\"GodoGen project ready\")\n")
    else:
        create(f"{args.name.replace(' ', '')}.csproj", '<Project Sdk="Godot.NET.Sdk/4.0.0"><PropertyGroup><TargetFramework>net8.0</TargetFramework><EnableDynamicLoading>true</EnableDynamicLoading></PropertyGroup></Project>\n')
        create("scripts/Main.cs", "using Godot;\npublic partial class Main : Node { public override void _Ready() => GD.Print(\"GodoGen project ready\"); }\n")
    manifest = {"schema_version": 1, "operation": "bootstrap", "created": created, "target": str(target), "language": args.language}
    write_json(target / ARTIFACT_DIR / "bootstrap-manifest.json", manifest)
    print(json.dumps(manifest, indent=2))
    return 0


def build(args: argparse.Namespace) -> int:
    project = Path(args.project).expanduser().resolve()
    ensure_project(project)
    artifact = project / ARTIFACT_DIR
    steps: list[dict[str, Any]] = []
    if project_language(project) == "csharp":
        steps.append(run(["dotnet", "build"], project, artifact / "dotnet-build.log", args.timeout))
        if steps[-1]["exit_code"] != 0:
            write_json(artifact / "build-report.json", {"schema_version": 1, "status": "failed", "steps": steps})
            return 1
    steps.append(run(["godot", "--headless", "--path", ".", "--import"], project, artifact / "godot-import.log", args.timeout))
    if steps[-1]["exit_code"] == 0:
        steps.append(run(["godot", "--headless", "--path", ".", "--quit"], project, artifact / "godot-smoke.log", args.timeout))
    status = "passed" if all(step["exit_code"] == 0 for step in steps) else "failed"
    write_json(artifact / "build-report.json", {"schema_version": 1, "status": status, "steps": steps})
    return 0 if status == "passed" else 1


def test(args: argparse.Namespace) -> int:
    project = Path(args.project).expanduser().resolve()
    ensure_project(project)
    artifact = project / ARTIFACT_DIR
    command = args.command or []
    if not command:
        if (project / "addons/gut").is_dir():
            command = ["godot", "--headless", "--path", ".", "-s", "addons/gut/gut_cmdln.gd"]
        elif list(project.glob("*.csproj")):
            command = ["dotnet", "test"]
        else:
            command = ["godot", "--headless", "--path", ".", "--quit"]
    result = run(command, project, artifact / "test.log", args.timeout)
    write_json(artifact / "test-report.json", {"schema_version": 1, "status": "passed" if result["exit_code"] == 0 else "failed", "result": result})
    return 0 if result["exit_code"] == 0 else 1


def capture(args: argparse.Namespace) -> int:
    project = Path(args.project).expanduser().resolve()
    ensure_project(project)
    artifact = project / ARTIFACT_DIR
    output = artifact / "video" / "proof.avi"
    output.parent.mkdir(parents=True, exist_ok=True)
    command = ["godot", "--path", ".", "--write-movie", str(output), "--fixed-fps", str(args.fps), "--quit-after", str(args.frames)]
    if args.scene:
        command.extend([args.scene])
    result = run(command, project, artifact / "capture.log", args.timeout)
    valid = output.exists() and output.stat().st_size > 1024
    report = {"schema_version": 1, "status": "passed" if result["exit_code"] == 0 and valid else "failed", "output": str(output), "bytes": output.stat().st_size if output.exists() else 0, "result": result}
    write_json(artifact / "capture-report.json", report)
    return 0 if report["status"] == "passed" else 1


def verify(args: argparse.Namespace) -> int:
    project = Path(args.project).expanduser().resolve()
    ensure_project(project)
    artifact = project / ARTIFACT_DIR
    required = ["build-report.json", "test-report.json"]
    if args.require_capture:
        required.append("capture-report.json")
    reports: dict[str, Any] = {}
    failures: list[str] = []
    for name in required:
        path = artifact / name
        if not path.is_file():
            failures.append(f"missing {name}")
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        reports[name] = data
        if data.get("status") != "passed":
            failures.append(f"{name} did not pass")
    hashes = {}
    for path in sorted(artifact.rglob("*")):
        if path.is_file() and path.name != "proof-report.json":
            hashes[str(path.relative_to(project))] = hashlib.sha256(path.read_bytes()).hexdigest()
    report = {"schema_version": 1, "status": "failed" if failures else "passed", "project": str(project), "failures": failures, "reports": reports, "artifact_sha256": hashes}
    write_json(artifact / "proof-report.json", report)
    summary = ["# GodoGen proof summary", "", f"Status: **{report['status'].upper()}**", ""]
    summary.extend([f"- {failure}" for failure in failures] or ["- Build and test gates passed."])
    (artifact / "proof-summary.md").write_text("\n".join(summary) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2))
    return 0 if not failures else 1


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(prog="godogen", description=__doc__)
    sub = root.add_subparsers(dest="command", required=True)
    boot = sub.add_parser("bootstrap")
    boot.add_argument("target")
    boot.add_argument("--name", default="GodoGenGame")
    boot.add_argument("--language", choices=["csharp", "gdscript"], default="csharp")
    boot.add_argument("--allow-non-empty", action="store_true")
    boot.set_defaults(func=bootstrap)
    for name, handler in (("build", build), ("test", test), ("capture", capture), ("verify", verify)):
        command = sub.add_parser(name)
        command.add_argument("--project", default=".")
        command.add_argument("--timeout", type=int, default=300)
        command.set_defaults(func=handler)
        if name == "test":
            command.add_argument("command", nargs=argparse.REMAINDER)
        elif name == "capture":
            command.add_argument("--scene")
            command.add_argument("--fps", type=int, default=30)
            command.add_argument("--frames", type=int, default=450)
        elif name == "verify":
            command.add_argument("--require-capture", action="store_true")
    return root


def main() -> int:
    args = parser().parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
